### PR TITLE
Advanced Mode in Model Trainer and some improvements  [Development Workbench]

### PR DESCRIPTION
**Pull request by akhil-rana**
## Description
- Browser based storage uses `blob` directly instead of base64 which should be faster and reliable.
- Support for larger custom dataset files is added using file chunks. **Works with** [SlideLoader #35](https://github.com/camicroscope/SlideLoader/pull/35)
- Toast alerts added at some places instead of classical browser ones.
- Some subtle changes

## Motivation and Context
- Improves stability and functionality. 

## How Has This Been Tested?
Briefly tested on Firefox (79.0), Chrome (84.0), Brave (1.10.x) on Windows 10 and Linux-LTS (arch - deepin)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by akhil-rana** [comment]
Though; workbench is still in development with many features to be added. But I think we might be able to merge `workbench` into `develop` after this. (:

**Comment by akhil-rana** [comment]
Since this is was active so I pushed here. I hope it's fine.

### Additions:
- Advanced Mode Toggle is given in the options in Model Trainer.
- The toggle enables various extra features/functions that might be useful for some advanced users.

Some Screenshots of advanced mode on/off are shown:

initial
layer Functions
conv2d

A demo: (Please ignore the flickering)
out

**Comment by birm** [comment]
It looks cool from the preview, I'll re-review.

**Comment by birm** [comment]
Wow @nanli-emory REALLY likes this PR :smile_cat:

**Comment by akhil-rana** [comment]
Thanks for the reviews. 😃

**Pull request merged**
