### PR TITLE
 Button Icons addition 

### PR DESCRIPTION
**Pull request by akhil-rana**
Icons are added in the upload and reload button using fontawesome.

Screenshot from 2020-03-30 06-59-20 (1)

### CODE REVIEW

**Comment by birm** [comment]
We just merged #273, did that not automatically reload the table data? Icons look good in any case :)

**Comment by mgautam98** [comment]
I already worked on that on #273 Please look at it

**Comment by mgautam98** [comment]
And location.reload() will reload the whole page. I used initilize() only the table part will be updated. Specifically, newly added slide.

**Comment by akhil-rana** [comment]
Oh sorry, I had the previous build before. 
Yes that works. My bad.

**Comment by birm** [comment]
Want to amend it to just include the icons then? :)

**Comment by akhil-rana** [comment]
yes. I have removed the other page reloading code as it was not needed.

**Comment by birm** [comment]
Thanks for the icons!

**Pull request merged**
