### PR TITLE
Fix for direct deletion of slide from admin account

### PR DESCRIPTION
**Pull request by Vedant1202**
This fix is related to [#368 ](https://github.com/camicroscope/caMicroscope/issues/368). 
solved

### CODE REVIEW

**Comment by birm** [comment]
Let me know when you want me to review.

**Comment by Vedant1202** [comment]
Yeah, you can do it now

**Comment by birm** [comment]
Thanks for the fix, and letting me know. I'm always nervous I'll review an unfinished PR.

**Comment by Vedant1202** [comment]
Haha yeah, asking's better

**Pull request merged**
