### PR TITLE
Fix for refresh table on first slide upload

### PR DESCRIPTION
**Pull request by Vedant1202**
A fix to [#337](https://github.com/camicroscope/caMicroscope/issues/337). 

This fix includes:
1.  Refresh page on first slide upload.
2. Check to make sure page does'nt refresh on concurrent slide uploads.

### CODE REVIEW

**Comment by cjchirag7** [comment]
@Vedant1202 , have you pulled the latest code from the **develop** branch of caMicroscope repo ?
Some of your fixes  like fixing the typo for 'return', fixing lint issues, has already been made earlier in #310

**Comment by cjchirag7** [comment]
@Vedant1202 , And why is it needed to refresh table on the first slide upload separately ? In #313 , I have updated the code to call initialize(), when 'post' of slide is successful, instead of reloading the whole page again.
One more thing, if you reload the whole page again, instead of calling initialize(), the popup showing 'Slide uploaded successfully' (added in #313 ) , would not work correctly.

**Comment by Vedant1202** [comment]
@cjchirag7 Yes, I have the latest pull from develop branch and the typo issue was just a merge fix, so it popped up.

**Comment by Vedant1202** [comment]
@cjchirag7 The initialize is not working during first slide upload. This is because it depends on a DOM element '#datatables' which does not exist in the first place (refer this [line](https://github.com/camicroscope/caMicroscope/blob/8b9bfc87704858d6b24fd5d59424569a7463960a/apps/table.html#L418)). 
A better fix to refreshing would be putting a condition to add the DOM element if it does not exist. 

Also I've kept in mind that the refresh is not interfering with the popup, as it is triggerred only after the popup gets hidden.

**Comment by cjchirag7** [comment]
@Vedant1202 , I noticed this. I have fixed in such a way that it adds the DOM element $('datatables) , when it doesn't exist, in #340

**Comment by Vedant1202** [comment]
Yeah, works

**Pull request closed without merging**
