### PR TITLE
Minor UI Changes

### PR DESCRIPTION
**Pull request by pranavbudhwant**
1. Status bar displays JSON as a table for better readability.
2. Thumbnail only displayed for 'Check'

### CODE REVIEW

**Comment by birm** [comment]
Minor change; can you add the thumbnail of each into the table?

**Comment by birm** [comment]
Actually, that can be a separate PR if you want (or not). Let me know when you want me to pull it in 👍

**Comment by pranavbudhwant** [comment]
@birm Sir I'll make the change, also maybe do a little formatting on the table, in a separate PR?

**Comment by birm** [comment]
Thank you for the good work!

**Pull request merged**
