### PR TITLE
Update bootstrap in table.html, workbench.html and info.html

### PR DESCRIPTION
**Pull request by Priyaraj17**
## Summary

Issue: #517 
I have updated the bootstrap versions in workbench.html, info.html, table.html files.

## Testing

image

### CODE REVIEW

**Comment by birm** [comment]
Hoping to review soon :)

**Comment by Priyaraj17** [comment]
Sure. Thanks

**Comment by birm** [comment]
It looks like the slide upload button/modal isn't working among similar issues, does this match your observation?

**Comment by akhil-rana** [comment]
Bootstrap 5 is major bump in bootstrap because it has ditched jQuery completely. And camic uses jquery a lot this needs to tested quite extensively I suppose.

**Comment by akhil-rana** [comment]
> Bootstrap 5 is major bump in bootstrap because it has ditched jQuery completely. And camic uses jquery a lot this needs to tested quite extensively I suppose.

**Addition**:  Workbench uses mdbootstrap so and it has bootstrap 4 as dependency I guess. So things should be tested carefully not just from a UI perspective but from a workflow perspective too.

**Comment by Priyaraj17** [comment]
Hey, I am also looking into the issue, the problem I am facing is only the slide upload button is not calling the on-click functions. I don't know if the problem is with bootstrap 5 as other buttons are working.

**Comment by birm** [comment]
Luckily, this isn't blocking anything, so we have plenty of time to test!

**Comment by akhil-rana** [comment]
> Luckily, this isn't blocking anything, so we have plenty of time to test!

Great

**Comment by Priyaraj17** [comment]
I am on it.

**Comment by Priyaraj17** [comment]
Hey guys, Things are working fine now... Apparently, bootstrap have updated a few things:
Earlier versions:
`<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>`
Bootstrap 5:
`<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>`
I have made the necessary changes. I hope I didn't miss anything.

**Review by birm — APPROVED** [review]
Looks good, thanks!

**Review by nanli-emory — APPROVED** [review]

**Pull request merged**
