### PR TITLE
Article missing in the Developer Guide

### PR DESCRIPTION
**Pull request by Creatoon**
## Description
This pr involves the addition of the article missing in the second line of the developer guide.

## Motivation and Context
**Why is this change required? What problem does it solve?
   Documentation update.

- If it fixes an open issue, please link to the issue here.
  This is not related to any issue.
## Types of changes
**What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
**Go over all the following points, and put an `x` in all the boxes that apply.
**(If you're unsure about any of these, don't hesitate to ask. We're here to help!)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by birm** [comment]
I do not believe this change to be correct. See [here](https://english.stackexchange.com/questions/12990/why-dont-we-use-the-indefinite-article-with-software#:~:text=2%20Answers&text=That's%20because%20software%20is%20uncountable,article%20(a%20or%20an).) for someone else's explanation/opinion at least.

**Comment by Creatoon** [comment]
@birm Sir, we are using the indefinite article ("an") before the "open-source" word, not before software, it is right that we should not use indefinite article before "software" .

Screenshot_2021-03-17 How to Use Articles (a an the) Purdue Writing Lab

Screenshot from 2021-03-17 12-20-39

**Comment by Creatoon** [comment]
@birm Sir, correct me if i am going wrong, thanks

**Comment by Creatoon** [comment]
@birm  Ok thanks, I got your point.

**Pull request closed without merging**
