### PR TITLE
Update README Documentation

### PR DESCRIPTION
**Pull request by sohamsshah**
## Description
The reference to setup Cloud Upload APIs for enabling the 'Upload from Drive' and similar features for caMicroscope that is available in the file - docs/cloudUploadAPIs.md is missing in the README.md

In this PR, it has been appended to the README.md file.

## Types of changes
**What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
**Go over all the following points, and put an `x` in all the boxes that apply.
**(If you're unsure about any of these, don't hesitate to ask. We're here to help!)
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by birm** [comment]
It looks like I can't review this until we either merge #477 or you cherry pick the relevant commits.

**Comment by sohamsshah** [comment]
I guess NanLi approved #477 . Can we merge that and then this can be reviewed?

**Comment by birm** [comment]
Does this intentionally also touch table.html?

**Comment by sohamsshah** [comment]
Only README.md is updated. You can ignore other changes :)

**Comment by sohamsshah** [comment]
Actually I tried cherry-picking the commits but due to some reason that resulted into conflicts and confusions. Since there were many issues with too many conflicting changes in this fork., I am closing this and will open a fresh PR for this change.

**Pull request closed without merging**
