### PR TITLE
Updated to bootstrap@5

### PR DESCRIPTION
**Pull request by Priyaraj17**
Issue: #517
## Summary

I have updated the version of bootstrap from 4.4.1 to 5.0.0. 
WhatsApp Image 2021-05-08 at 11 48 56 AM

## Motivation

The latest version of bootstrap is 5.0.0 and caMicrscope currently uses 4.4.1. 
I also worked on improvement in the responsiveness of the application for the smaller screens. I added a few css styles to make the UI more attractive.

## Testing

UI:
Desktop:
WhatsApp Image 2021-05-08 at 11 42 12 AM
I PhoneX
WhatsApp Image 2021-05-08 at 11 42 59 AM

Sign-Up page:
Smal screens:
WhatsApp Image 2021-05-08 at 11 47 05 AM

### CODE REVIEW

**Comment by Priyaraj17** [comment]
Hey, @birm @akhil-rana can you please check this... If this is okay? Or any suggestions?

Thank you

**Review by birm — CHANGES_REQUESTED** [review]
In signup, I'm seeing an issue with the viewer type selection box's style.

image

**Comment by Priyaraj17** [comment]
I might have missed this. I will make the necessary changes. Thanks!

**Comment by Priyaraj17** [comment]
Hey @birm, I have made the required changes.

**Pull request merged**
