### PR TITLE
Model summary

### PR DESCRIPTION
**Pull request by AbdulRashidReshamwala**
Added visualisation of the model which is currently loaded for prediction
Will show the current model architecture being used
Can be easily toggled on/off
Screenshots
Screenshot from 2020-03-25 21-33-27

### CODE REVIEW

**Comment by birm** [comment]
It looks like this topic branch was forked from your previous topic branch, so some commits are duplicated.

**Comment by AbdulRashidReshamwala** [comment]
@birm How do I fix that that ?

**Comment by birm** [comment]
Try a hard reset to the point before your modifications, then re-add your relevant changes. Then you can force-push. Let me know if you need more specific instructions.

**Comment by AbdulRashidReshamwala** [comment]
@birm more specific instructions would be great

**Comment by birm** [comment]
Make a copy outside of the git repo of the file you modified, then, in your fork
```
git reset --hard 39d2d683
# Add back your changes then...
git commit -m "Model Summary"
git push --force-with-lease
```
The first command rewinds back to the given commit hash
The force/force-with-lease is necessary since git wants to make sure you actually mean to make that kind of change.

**Comment by AbdulRashidReshamwala** [comment]
Done thanks for the help

**Comment by birm** [comment]
Awesome! I'll bug @Insiyaa for a review.

**Comment by Insiyaa** [comment]
Issues: 
- The panel opens on loading the app, covering up the selection area
- Once hidden, no button to view it again
Please, look into these.

**Comment by AbdulRashidReshamwala** [comment]
@insiyaa You can easily toggle the section by pressing '~' on your keyboard 
Currently internet is shut in my region will show an alert notifying user about this action.

**Comment by Insiyaa** [comment]
Adding a button to toggle would be better, take your time :)

**Comment by AbdulRashidReshamwala** [comment]
@Insiyaa i have fixed both of the issues.

**Comment by Insiyaa** [comment]
Great! Could you reflect the same changes in segment.js? 
Also, you may choose another icon from [these](https://material.io/resources/icons/).

**Comment by AbdulRashidReshamwala** [comment]
@birm completed the requested changes

**Pull request merged**
