### PR TITLE
Added aria-label to toolbar icons

### LINKED ISSUE #981: [Accessibility] Slide Viewer: Tool icons on top left don't have contextual labels/names.
**Describe the bug**
Screen reader calls out a different name from what the tool tip shows when you place a mouse on the icons in the toolbar. For instance, the "draw" icon is read as "create", the "magnifier" icon as "search". 

**Expected behavior**
Icons should have contextual and corresponding labels/names.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by nwanduka**
## Summary

This PR fixes #981

### CODE REVIEW

**Comment by nwanduka** [comment]
I don't think I understand what you mean. Are you saying you can't "see" the aria-label or when testing with a screen reader, the aria-label isn't called out?

Also could you tell me how you're viewing the changes made? I'd like to be able to confirm that any changes I made work as intended before creating a PR. I don't know how to. Or you could point me to a resource material. Any would be helpful.

**Comment by birm** [comment]
The issue that I noticed is that the html for the toolbar icons wasn't including the aria label. I think I've added it in [6dafdf6](https://github.com/camicroscope/caMicroscope/pull/1010/commits/6dafdf62178f34384c4819c5cc96a1fb24d4fa36); please let me know if you agree or not :)

**Comment by nwanduka** [comment]
Ohhhkay. I get it. I missed that. Thanks for pointing it out. And fixing it 😊

**Comment by birm** [comment]
Does it look ok to merge to you?

**Comment by nwanduka** [comment]
Yes, looks good to me. Ready to merge.

**Review by birm — APPROVED** [review]

**Pull request merged**
