### PR TITLE
Email Validation

### PR DESCRIPTION
**Pull request by mgautam98**
This solves #257
Apart from that, When It was giving error alert was popping up. So, to improve user experience I did the following
Annotation 2020-03-27 052705

The error will show above. Tell me if you want any changes to this.

### CODE REVIEW

**Comment by birm** [comment]
Ah, just as we merged something touching the same files! Can you resolve the merge conflict?

**Comment by mgautam98** [comment]
Okay

**Comment by mgautam98** [comment]
@birm you can close this as the all the issues are addressed in the previous pr also #257  
Thank You

**Comment by birm** [comment]
Oh, I'm sorry about the conflict! Thanks for your effort in any case!

**Pull request closed without merging**
