### PR TITLE
add model memory usage logs in apps/model

### PR DESCRIPTION
**Pull request by AbdulRashidReshamwala**
Added model memory usage logs mentioned in https://github.com/camicroscope/caMicroscope/issues/215

### CODE REVIEW

**Comment by AbdulRashidReshamwala** [comment]
@birm @Insiyaa any idea why the tests failed ?

**Comment by birm** [comment]
I'm not sure, but the tests passed locally, and it seems to have nothing to do with your changes
```
➜  camicroscope git:(AbdulRashidReshamwala/memory-loging) ✗ mocha test --recursive


  Ca Message Component
    ✓ Initialize
    ✓ Change Text
    ✓ Change Style

  Collapsible List Component
    constructor:options
      ✓ has two heads and contents
      ✓ item1 is expand
      ✓ item2 is collapse
      ✓ item1 has checkbox [checked] and div [textContent = 1111]
      ✓ item2 has a input and text value is text input
    triggerContent(itemId,action)
      ✓ triggerContent('item2','open')
      ✓ triggerContent('item1')
    addContent(itemId, elt)
      ✓ add stringified HTMLelement to the content
      ✓ add HTMLElement to the content
    clearContext(itemId)
      ✓ clear item1's content
    callback function
      ✓ open item2
      ✓ open item1
      ✓ simulate a click event on the item1's head, which closes item1
    setList(list)
      ✓ has three heads and contents
      ✓ item3 is expand
      ✓ item1 and item2 are collapse
      ✓ item1 has three divs
      ✓ item2 has a h1 and textContent is hahahah
      ✓ item3 has a input.type=range
    After setList: triggerContent(id,action)
      ✓ triggerContent('item2','open')
      ✓ triggerContent('item2')
    After setList: addContent(itemId, elt)
      ✓ add stringified HTMLelement to the content
      ✓ add HTMLElement to the content
    After setList: clearContext(itemId)
      ✓ clear item1's content
    After setList: callback function
      ✓ open item2
      ✓ open item1
      ✓ simulate a click event on the item1's head, which closes item1

  Message Queue Component
    constructor:options
      ✓ position:top-left(default)
      ✓ position:top-right
      ✓ position:bottom-left
      ✓ position:bottom-right
    add(text, time)
      ✓ text and css
    addWarning(text, time)
      ✓ text and css
    addError(text, time)
      ✓ text and css
    multiple messages
      ✓ matching the number of messages
      ✓ each text and css

  Mult-Selector Component
    constructor
      ✓ window.mSel1: no control
      ✓ window.mSel1: no options
      ✓ window.mSel2: has control
      ✓ window.mSel2: has options
    setData()
      ✓ setData():valid data
    events
      ✓ event:select
[ [ '0', 'opt0' ], [ '1', 'opt1' ] ]
      ✓ event:remove
      ✓ event:action
      ✓ event:cancel
      ✓ event:select-all
      ✓ event:remove-all
    getSelected()
      ✓ Nothing selected
      ✓ Something selected

  Operation Panel Component
    constructor:options
      ✓ Options Error: No Schema Error
      ✓ Options Error: No Action Error
      ✓ Options:check action's text and states
      ✓ Options:check callback
    Schema Setting
      ✓ Check schema's default value
      ✓ Check validation on form
    Callback Function
      ✓ click On Save
    multiple schemas
      ✓ Form Select changed
      ✓ Callback Function

  Side Menu Component
    constructor:options[default]
      ✓ menu close
    constructor:options(isOpen:true,width:500px)
      ✓ menu open and width is 500px
    addContext(String/Element)
      ✓ the number of content's children matching
      ✓ children's textContent are correct
    clearContext()
      ✓ all contents was clear
    callback function
      ✓ open menu1
      ✓ close menu2
      ✓ simulate a click event on the close button

  Toolbar Component
    constructor:options[default]
      ✓ style
      ✓ li > states
      ✓ handler events
    click events for each tool
      ✓ main tool click events
      ✓ btn tool click events
      ✓ check tool click events
      ✓ multistates tool click events
{ value: 'dropdown', checked: true, status: 'a' }
      ✓ dropdown tool click events


  77 passing (1s)
```

**Comment by birm** [comment]
@Insiyaa I'll approve if you do :)

**Comment by leoarc** [comment]
There is already a ``` var memory ```  [here](https://github.com/camicroscope/caMicroscope/blob/631fd9220510ac07362d5ec47115bc1fde98ab84/apps/model/model.js#L376). You're redefining it as ``` const ``` . I think thats why CI test is failing

**Comment by Insiyaa** [comment]
Good to go!

**Pull request merged**
