### PR TITLE
[New Feature]Screenshot of slide

### PR DESCRIPTION
**Pull request by Hemansh31**
## Description
**Describe your changes in detail

This screenshot feature helps user to take screenshot of the slide and download it as an image.

## Motivation and Context
**Why is this change required? What problem does it solve?

- This is useful as screenshots of slides are required by several users as they need to be included in reports or research papers.

*Note :* 
This is the first and basic version of screen capture. Next step in this includes adding functionality to capture only a selected area of the slide. We can also add the functionality to include annotations in the screen capture.

## How Has This Been Tested?
**Please describe in detail how you tested your changes.
- I tested it on my local setup

## Screenshots (if appropriate):
screenshare

## Types of changes
**What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
**Go over all the following points, and put an `x` in all the boxes that apply.
**(If you're unsure about any of these, don't hesitate to ask. We're here to help!)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nanli-emory** [comment]
hoping you can continuously work and improve on the screenshot feature which includes annotations/ heatmap/ segmentations. Good job.

**Review by nanli-emory — APPROVED** [review]

**Comment by Hemansh31** [comment]
@nanli-emory @birm I have added support for including annotations in the screenshot. Here is the example

Untitled_ Feb 17, 2021 7_39 PM

**Review by birm — APPROVED** [review]
Thanks for the new feature. Mind resolving the conflict?

**Comment by Hemansh31** [comment]
@birm i made an error while resolving the conflict so i reverted the commit. How do I again resolve the conflict as I cannot see the option now

**Comment by Hemansh31** [comment]
i think i'll have to open a new pull request, my bad :(

**Comment by birm** [comment]
oh no, I'm sorry!

**Pull request closed without merging**
