### PR TITLE
Remove camel case ignore rule in ESLint

### PR DESCRIPTION
**Pull request by cjchirag7**
Fixes a subissue of #274 
I have made sure that the application works, as earlier.
@birm , please review.

### CODE REVIEW

**Comment by cjchirag7** [comment]
@birm , @nanli-emory , the required changes have been made

**Comment by birm** [comment]
See https://github.com/camicroscope/caMicroscope/blob/75561aff1c5c259b502774da8566e9e3d2d92318/apps/viewer/init.js#L1010 for reset_callback and anno_callback

**Comment by cjchirag7** [comment]
@birm thanks for the review ! I checked all the html and js files once again and found some more changes to be required in table.html and init.js. I have made the required changes. I think now it should be fine.

**Comment by cjchirag7** [comment]
@birm , I have updated this PR to resolve merge conflicts. Please review.

**Pull request merged**
