### PR TITLE
Initial Implementation of batch slide loader

### PR DESCRIPTION
**Pull request by akhil-rana**
## Description
- A new batch slide loader app page has been created at `/apps/batchloader/` to upload multiple files simultaneously with ease.
- Slide name can be generated by the user provided name eg. `sample_1`,`sample_2` etc.
- File names can either be set to default (original file names) or can be generated similar to the slide name.
- This is an initial implementation and I look forward to suggestions and feedback.
- Working on better implementation of validation and error handling.
- Some functions in `batchLoader.js` are modified from `chunked_loader.js` and `loader.js` to behave accordingly since I was trying to solve the issue without making changes in slideLoader(at least for now).
## Motivation and Context
**Why is this change required? What problem does it solve?
- In reference to #352 

## How Has This Been Tested?
- Tested on Mozilla 75.0, Chrome 81.0
- Ubuntu 19.10

## Screenshots (if appropriate):

Please click on the gif to view in full screen if not visible clearly here.

chrome-2020-04-19_03 45 16-_online-video-cutter com_-min

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by akhil-rana** [comment]
@birm 
Am I heading in the right direction here?

**Comment by birm** [comment]
That's pretty cute! I'll review it more deeply in a bit.

**Comment by birm** [comment]
One little change for now; can we add a column which shows what the filename of the original file was?

**Comment by akhil-rana** [comment]
Thank you.
I will be working on this to improve this more further.

**Pull request merged**
