### PR TITLE
Batch Loader Enhancement 

### PR DESCRIPTION
**Pull request by akhil-rana**
## Description
Some features are added to the batch loader:
- Delete Functionality to remove the slide.
- Individual Slidename and FIlename change functionality.
- `Info` icon is added which to every row which on click describes various information about the slide like `original filename`, `filename` , `slide name`, `status`, `token` etc.
- Filename/slidename validation during individual edit.

## Motivation and Context
- Improving BatchLoader and working in reference to #352.

## How Has This Been Tested?
Tested on: 
- Mozilla 75.0, Chrome 81.0
- Ubuntu 19.10

## Screenshots:

chrome-2020-04-20_09 13 27

chrome-2020-04-20_09 09 13

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by akhil-rana** [comment]
@birm 
About the original file name. I have added it inside the `Slide info` 
If you think that a new column should be added for the same, please let me know.

**Comment by akhil-rana** [comment]
Thanks for the review.
I'm working on those. 
And some more minor things. Will push the changes soon.

**Comment by birm** [comment]
Of course, since this is an early app, there are still some things to hammer out. Up to you how much/little goes into each PR. (For example, the batch slide name field could be smart enough to borrow the file extension from the original filenames)

**Comment by birm** [comment]
I think it's reasonable to have it use the source's file extension, though if someone goes in to manually change it, that's on them :)

**Pull request merged**
